// <auto-generated />
namespace ClinicManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedtinydetailsindoctor214 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedtinydetailsindoctor214));
        
        string IMigrationMetadata.Id
        {
            get { return "202204032039371_Added tiny details in doctor 2.1.4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
